connectedin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
)

perfis/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from perfis import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convidar'),
    url(r'^convite/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='aceitar'),
)

usuarios/urls.py
from django.conf.urls import patterns, url
from usuarios.views import RegistrarUsuarioView

urlpatterns = patterns('',
                       url(r'^registrar/$', RegistrarUsuarioView.as_view(), name="registrar"),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
                       url(r'^logout/&', 'django.contrib.auth.views.logout_then_login', {'login_url': '/login/'}, name='logout')
                       )

perfis/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name="perfil")

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        convite = Convite(solicitante=self, convidado=perfil_convidado).save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.CharField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados!')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuário já cadastrado no banco')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

perfis/views.py
from django.shortcuts import render, redirect
from perfis.models import Perfil, Convite
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'index.html', {'perfis': Perfil.objects.all(), 'perfil_logado': get_logged(request)})


@login_required
def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_logged(request)
    is_contato = perfil in perfil_logado.contatos.all()
    return render(request, 'perfil.html', {"perfil": perfil, 'is_contato': is_contato})


@login_required
def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_logged(request)
    perfil_logado.convidar(perfil_a_convidar)
    return redirect('index')


@login_required
def get_logged(request):
    return request.user.perfil


@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm


class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):

		#preenche form
        form = RegistrarUsuarioForm(request.POST)

        #check if is valid
        if form.is_valid():
            dados_form = form.data

            #create user
            usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])

            #create perfil
            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)
            #save
            perfil.save()

            return redirect('index')

        return render(request, self.template_name, {'form': form})

perfis/templates/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
	<title>ConnecteIn</title>
	<link rel="stylesheet" type="text/css" href="{% static "styles/bootstrap.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "styles/main.css" %}">
</head>
<body>

	<div class="container">
		<div class="header">
			<ul class="nav nav-pills pull-right">
				<li><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
				<li><a href="/logout/">Logout</a></li>
			</ul>
			<h3 class="text-muted">ConnecteIn</h3>
		</div>

		<div class="row content">
			{% block body %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

perfis/templates/index.html
{% extends "header.html" %}
{% block body %}
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os Perfis</strong>
		</div>
		{% if perfis %}
			<ul>
				{% for perfil in perfis %}
				<li>
					<a href="{% url 'exibir' perfil.id %}">{{ perfil.nome }}</a>
					<p>{{ perfil.telefone }}</p>
				</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>Nenhum perfil encontrado</p>
		{% endif %}
	</div>
	<div class="panel panel-default">
		{% with total_convites=perfil_logado.convites_recebidos.count %}
			{% if total_convites %}
				<div class="panel-heading">
					<strong>Você tem {{ total_convites }} convite{{total_convites |pluralize}}  para aceitar</strong>
					<ul class="list-group">
						{% for convite in perfil_logado.convites_recebidos.all %}
							<li class="list-group-item">
								{{ convite.solicitante.nome }}
								<a href="{% url 'aceitar' convite.id %}" class="pull-right">Aceitar</a>
							</li>
						{% endfor%}
					</ul>
				</div>
			{% else %}
				<div class="panel-body">
					<p>Nenhum convite recebido</p>
				</div>
			{% endif %}
		{% endwith %}
	</div>

	<div class="panel panel-default">
		{% with total_contatos=perfil_logado.contatos.count %}
			{% if total_contatos %}
				<div class="panel-heading">
					<strong>Você tem {{ total_contatos }} contato{{total_contatos |pluralize}}</strong>
					<ul class="list-group">
						{% for contato in perfil_logado.contatos.all %}
							<li class="list-group-item">
								<a href="{% url 'exibir' contato.id %}">
									{{ contato.nome }}
								</a>
							</li>
						{% endfor%}
					</ul>
				</div>
			{% else %}
				<div class="panel-body">
					<p>Nenhum contato</p>
				</div>
			{% endif %}
		{% endwith %}
	</div>
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "header.html" %}
{% block body %}

	<div class="row">
		<dir class="col-lg-12">
			<h2 style="margin-top: 0">{{ perfil.nome }}</h2>
			<address>
				<strong>{{ perfil.nome_empresa }}</strong>
				<abbr title="Telefone">Tel.:</abbr>{{ perfil.telefone}} 
			</address>
			{% if is_contato %}
				<div class="well well-sm">
					Vocês estão conectados
				</div>
			{% else %}
				<a href="{% url 'convidar' perfil.id %}">
					Convidar
				</a>
			{% endif %}
		</dir>
	</div>

{% endblock %}

usuarios/templates/base_user.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <title>ConnectedIn</title>

        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

usuarios/templates/login.html
{% extends "base_user.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'django.contrib.auth.views.login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

usuarios/templates/registrar.html
{% extends "base_user.html" %}

{% block body %}

  <form class="form-signin" role="form" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}

    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" placeholder="Email *" value="{{form.email.value}}" required autofocus >

    <input type="password" id="id_senha" name="senha" class="form-control"  placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" value="{{form.nome.value}}" required >

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" value="{{form.telefone.value}}">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" value="{{form.nome_empresa.value}}">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    <hr/>

     {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        {{form.non_field_errors}}
      </div>
    {% endif %}
  </form>

{% endblock %}